import mongoose from "mongoose";

const CallSchema = new mongoose.Schema(
  {
    // Stable client-facing call identifier generated by CallSocket.js
    // (separate from Mongo's _id). Indexed + unique since clients/REST
    // routes look calls up by this, not by _id.
    callId: {
      type: String,
      required: true,
      unique: true,
      index: true,
    },

    conversationId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Conversation",
      required: true,
      index: true,
    },

    caller: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true,
    },

    receiver: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true,
    },

    // CallSocket.js defaults this to "audio", not "voice"
    type: {
      type: String,
      enum: ["audio", "video"],
      default: "audio",
    },

    // Union of every status CallSocket.js actually persists:
    // - "missed"    -> call:no-answer timeout
    // - "cancelled" -> call:cancel (caller hung up before answer)
    // - "rejected"  -> call:reject (receiver declined)
    // - "busy"      -> call:busy (receiver already on another call)
    // - "completed" -> call:end (normal hangup after connecting)
    // - "ended"     -> disconnect (abrupt drop; see note below on
    //                  distinguishing ringing-drop vs connected-drop)
    status: {
      type: String,
      enum: [
        "ringing",
        "connected",
        "completed",
        "missed",
        "cancelled",
        "rejected",
        "busy",
        "ended",
      ],
      required: true,
      index: true,
    },

    startedAt: {
      type: Date,
      default: null,
    },

    endedAt: {
      type: Date,
      default: null,
    },

    duration: {
      type: Number,
      default: 0,
    },
  },
  {
    timestamps: true,
  }
);

export default mongoose.model("Call", CallSchema);