name: Dev - Build & Deploy

on:
  push:
    branches: [ dev ]

jobs:
  build-and-deploy-dev:
    runs-on: [self-hosted, windows]
    steps:
      # 1. Checkout repo
      - uses: actions/checkout@v3

      # 2. Setup Node
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Install dependencies
      - name: Install dependencies
        shell: pwsh
        run: |
          try {
            npm ci --omit=dev
          } catch {
            npm install --production
          }

      # 4. Build (optional)
      - name: Build (if present)
        shell: pwsh
        run: |
          if (Test-Path package.json) {
            npm run build --if-present
          }

      # 5. Deploy to dev/staging
      - name: Deploy to staging
        shell: pwsh
        run: |
          pwsh .\scripts\deploy.ps1 -env 'development' -appName 'LifePulse-dev'
