name: Dev - Build & Deploy

on:
  push:
    branches: [ dev ]

jobs:
  build-and-deploy-dev:
    runs-on: [self-hosted, windows]

    steps:
      # 1. Checkout repo (system config avoids .gitconfig issue)
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup Git config
        run: |
         git config --global user.name "github-actions[bot]"
         git config --global user.email "github-actions[bot]@users.noreply.github.com"
         shell: powershell


      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Ensure PM2 is installed globally
      - name: Install PM2
        run: npm install -g pm2
        shell: powershell

      # 4. Install dependencies for backend
      - name: Install dependencies
        run: npm install
        working-directory: Backend
        shell: powershell

      # 5. Deploy with PM2 (HOME explicitly set inside script)
      - name: Deploy to staging
        run: .\scripts\deploy.ps1 -env 'development' -appName 'LifePulse-dev'
        shell: powershell
