name: Dev - Build & Deploy

on:
  push:
    branches: [ dev ]

jobs:
  build-and-deploy-dev:
    runs-on: [self-hosted, windows]

    steps:
      # 1. Checkout repo
      - uses: actions/checkout@v3

      # 2. Setup Node
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Install dependencies
      - name: Install dependencies
        shell: cmd
        run: npm install
        working-directory: Backend

      - name: Add pm2 to PATH
        shell: powershell
        run: |
         $env:Path += ";C:\nvm4w\nodejs"
         [System.Environment]::SetEnvironmentVariable("Path", $env:Path, [System.EnvironmentVariableTarget]::Process)
         pm2.cmd -v



      # 5. Deploy to dev/staging
      - name: Deploy to staging
        shell: powershell
        run: .\scripts\deploy.ps1 -env 'development' -appName 'LifePulse-dev'
