name: Dev - Build & Deploy

on:
  push:
    branches: [ dev ]

jobs:
  build-and-deploy-dev:
    runs-on: [self-hosted, windows]
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
  run: |
    if (!(npm ci --omit=dev)) {
      npm install --production
    }
  shell: pwsh


      - name: Build (if present)
        run: npm run build --if-present

      - name: Deploy to staging
        shell: pwsh
        run: pwsh .\scripts\deploy.ps1 -env 'development' -appName 'LifePulse-dev'
