name: Prod - Build & Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy-prod:
    runs-on: [self-hosted, windows]
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies (production)
        run: npm ci --omit=dev || npm install --production

      - name: Build (if present)
        run: npm run build --if-present

      - name: Deploy to production
        shell: pwsh
        run: pwsh .\scripts\deploy.ps1 -env 'production' -appName 'LifePulse-prod'
