name: Prod - Build & Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy-prod:
    runs-on: [self-hosted, windows]
    steps:
      # 1. Checkout repo
      - uses: actions/checkout@v3

      # 2. Setup Node
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Install dependencies
      - name: Install dependencies
        shell: cmd
        run: |
            npm install

      # 4. Build (optional, safe check)
      - name: Build (if present)
        shell: cmd
        run: |
          if (Test-Path package.json) {
            npm run build
          }

      # 5. Deploy (custom PowerShell script)
      - name: Deploy to production
        shell: pwsh
        run: |
          pwsh .\scripts\deploy.ps1 -env 'production' -appName 'LifePulse-prod'
